name: tractian
description: "Tractian Challenge."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  provider: ^6.1.2
  http: ^1.2.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/company.png
    - lib/assets/component.png
    - lib/assets/subcomponent.png
    - lib/assets/location.png
 
